server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:db/master.yml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/sentryc-graphql-test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver